spring.application.name=az.developia
server.port=8082

spring.jpa.hibernate.ddl-auto=update
springdoc.override-with-generic-response=false

spring.datasource.url=jdbc:h2:mem:file
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=root
spring.datasource.password=123456d
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect


spring.h2.console.enabled=true
spring.h2.console.path=/h2-console
